package io.therapistai.memory.domain;

public enum MemoryKey {

    // PERSON
    NAME,
    AGE,
    DATE_OF_BIRTH,
    GENDER,
    NATIONALITY,
    LANGUAGE,
    ROLE,
    DESCRIPTION,

    // WORK_STATUS
    EMPLOYMENT_STATUS,
    JOB_TITLE,
    COMPANY,
    INDUSTRY,
    WORK_MODE,
    UNEMPLOYMENT_DURATION,
    JOB_SEARCH_STATUS,
    WORK_STRESS,
    CAREER_CONCERN,

    // SCHOOL_STATUS
    EDUCATION_STATUS,
    SCHOOL_NAME,
    FIELD_OF_STUDY,
    ACADEMIC_LEVEL,
    ACADEMIC_CONCERN,

    // FINANCIAL_STATUS
    FINANCIAL_SITUATION,
    DEBT_STATUS,
    INCOME_STATUS,
    FINANCIAL_CONCERN,
    FINANCIAL_DEPENDENCY,

    // LIVING_SITUATION
    COUNTRY,
    CITY,
    HOUSEHOLD,
    LIVING_ARRANGEMENT,
    HOUSING_CONCERN,

    // RELATIONSHIP_STATUS
    MARITAL_STATUS,
    PARTNERSHIP_STATUS,
    RELATIONSHIP_QUALITY,
    CURRENT_CONFLICT,
    SEPARATION_STATUS,

    // SUPPORT_SYSTEM
    SUPPORT_PERSON,
    SUPPORT_ROLE,
    SUPPORT_TYPE,
    SUPPORT_AVAILABILITY,

    // PREFERENCE
    PREFERENCE_TYPE,
    PREFERENCE_VALUE,

    // LIFE_EVENT
    EVENT_TYPE,
    EVENT_DATE,
    IMPACT,
    STATUS,

    // CHILDHOOD_BACKGROUND
    FAMILY_STRUCTURE,
    PARENT_RELATIONSHIP,
    CHILDHOOD_EVENT,
    CHILDHOOD_DESCRIPTION,

    // CORE_BELIEF
    BELIEF,
    BELIEF_DOMAIN,

    // IDENTITY
    IDENTITY_STATEMENT,
    IDENTITY_DOMAIN,
    SELF_DESCRIPTION,

    // THERAPY_GOAL
    GOAL,
    GOAL_PRIORITY,
    GOAL_PROGRESS,

    // THERAPY_TOPIC
    TOPIC,
    TOPIC_FREQUENCY,
    TOPIC_IMPORTANCE,

    // THERAPY_EXPECTATION
    EXPECTATION,
    EXPECTATION_PRIORITY,

    // COPING
    COPING_STRATEGY,
    COPING_EFFECTIVENESS,
    COPING_CONSEQUENCE,
    COPING_FREQUENCY,

    // SYMPTOM
    SYMPTOM_NAME,
    SEVERITY,
    FREQUENCY,
    DURATION,

    // TRIGGER
    TRIGGER_SOURCE,
    TRIGGER_CONTEXT,
    TRIGGER_INTENSITY,

    // FEAR
    FEAR_OBJECT,
    FEAR_CONTEXT,
    FEAR_INTENSITY,

    // STRESSOR
    STRESSOR_SOURCE,
    STRESSOR_CONTEXT,
    STRESS_LEVEL
}